config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'
  get 'privacy', to: 'tops#privacy'
  get 'terms', to: 'tops#terms'

  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :results, only: %i[show create] do
    member do
      get 'loginresults'
      get 'likeresults'
    end
    collection do
      get :likes
    end
  end

  resources :ranks, only: %i[index] do
    member do
      get 'record'
      get 'login_record'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :diaries

  resources :users do
    resources :attachments, controller: 'users/attachments', only: %i[destroy]
  end
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :start_time, presence: true
  validates :body, presence: true, length: { maximum: 65_535 }
  validates :score, numericality: { only_integer: true }, presence: true
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :require_login

  def index
    @diaries = Diary.all
  end

  def new
    @diary = Diary.new
  end

  def show
    @diary = Diary.find(params[:id])
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user_id = current_user.id if logged_in?
    if @diary.save
      redirect_to diaries_path, info: '日記の登録に成功しました'
    else
      flash.now[:warning] = '日記の登録に失敗しました'
      render new_diary_path
    end
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to diaries_path, danger: '日記を削除しました'
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      redirect_to diaries_path, info: '編集しました'
    else
      render 'edit'
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:title, :body, :start_time, :score, :user_id)
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/edit.html.erb
<div id='container-user'>
  <div class='lead'>
    <h1>記録編集</h1>
  </div>
  <div class='wrapper user'>
    <%= form_with model: @diary do |f| %>
      <%= render 'layouts/error_messages', object: f.object %>
      <div class='form-group1'>
        <%= f.label :title, class: 'col-sm-4 control-label' %>
        <%= f.text_field :title %>
      </div>

      <div class='form-group2'>
        <%= f.label :start_time, class: 'col-sm-4 control-label' %>
        <%= f.date_field :start_time %>
      </div>

      <div class='form-group3'>
        <%= f.label :score, class: 'col-sm-4 control-label' %>
        <%= f.number_field :score %>
      </div>

      <div class='form-group4'>
        <%= f.label :body, class: 'col-sm-4 control-label' %>
        <%= f.text_area :body, size: '20x5' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-outline-primary login' %>
    <% end %>
  </div>
</div>

app/views/diaries/index.html.erb
<div id='container-user'>
  <div class='lead'>
    <h1>しつけ成長記</h1>
  </div>

  <%= link_to '記録する', new_diary_path, class: 'btn btn-success record' %>

  <%= month_calendar events: @diaries do |date, diaries| %>
    <%= date.day %>

    <% diaries.each do |diary| %>
      <div>
        <%= link_to diary.title, diary %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/diaries/new.html.erb
<div id='container-user'>
  <div class='lead'>
    <h1>しつけ記録</h1>
  </div>
  <div class='wrapper user'>
    <%= form_with model: @diary do |f| %>
      <%= render 'layouts/error_messages', object: f.object %>
      <div class='form-group1'>
        <%= f.label :title, class: 'col-sm-6 control-label' %>
        <%= f.text_field :title %>
      </div>

      <div class='form-group2'>
        <%= f.label :start_time, class: 'col-sm-6 control-label' %>
        <%= f.date_field :start_time %>
      </div>

      <div class='form-group3'>
        <%= f.label :score, class: 'col-sm-6 control-label' %>
        <%= f.number_field :score %>
      </div>

      <div class='form-group4'>
        <%= f.label :body, class: 'col-sm-6 control-label' %>
        <%= f.text_area :body, size: '20x5' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-outline-primary login' %>
      <% end %>
  </div>
</div>

app/views/diaries/show.html.erb
<div id='container-user'>
  <div class='lead'>
    <h1>詳細</h1>
  </div>
  <div class='wrapper user'>
    <h1 class='dairy'>しつけた内容</h1>
    <div class='form-group5'>
    <p><%= @diary.title %></p>
    </div>

    <h1 class='dairy'>日付</h1>
    <div class='form-group5'>
      <p><%= @diary.start_time.strftime("%Y年-%m月-%d日") %></p>
    </div>

    <h1 class='dairy'>自己採点</h1>
    <div class='form-group5'>
      <p><%= @diary.score %>点</p>
    </div>

    <h1 class='dairy'>詳細</h1>
    <div class='form-group5'>
      <p><%= simple_format(@diary.body) %></p>
    </div>
    
    <%= link_to '編集する', edit_diary_path(@diary), class: 'btn btn-dark btn-rounded' %>
    <%= link_to '削除する', diary_path(@diary), method: :delete, data: { confirm: '削除してもよろしいですか？' }, class: 'btn btn-danger btn-rounded destroy' %>
    <%= link_to '戻る', diaries_path, class: 'btn btn-light btn-rounded' %>
  </div>
</div>