config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'
  get 'privacy', to: 'tops#privacy'
  get 'terms', to: 'tops#terms'

  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :results, only: %i[show create] do
    member do
      get 'loginresults'
      get 'likeresults'
    end
    collection do
      get :likes
    end
  end

  resources :ranks, only: %i[index] do
    member do
      get 'record'
      get 'login_record'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :diaries

  resources :users do
    resources :attachments, controller: 'users/attachments', only: %i[destroy]
  end
end

app/models/result.rb
class Result < ApplicationRecord
  include IdGenerator

  belongs_to :user
  belongs_to :rank
  has_one :like, dependent: :destroy

  has_one_attached :record_voice

  validates :score, numericality: { only_integer: true }, presence: true
  validates :calm, numericality: { only_integer: true }, presence: true
  validates :anger, numericality: { only_integer: true }, presence: true
  validates :joy, numericality: { only_integer: true }, presence: true
  validates :sorrow, numericality: { only_integer: true }, presence: true
  validates :energy, numericality: { only_integer: true }, presence: true

  def start_time
    self.start_date
  end

  def empath(formdata)
    conn = Faraday::Connection.new('url': ENV['API_URL']) do |f|
      f.request :multipart
      f.request :url_encoded
      f.response :logger
      f.adapter Faraday.default_adapter
    end

    response = conn.post do |req|
      req.body = {
        apikey: ENV['API_KEY'],
        wav: Faraday::Multipart::FilePart.new(formdata[:record_voice], 'audio/wav')
      }
    end
    judge(formdata, response)
  end

  def judge(formdata, response)
    hash = JSON.parse(response.body)
    self.calm = hash['calm']
    self.anger = hash['anger']
    self.joy = hash['joy']
    self.sorrow = hash['sorrow']
    self.energy = hash['energy']
    self.rank_id = formdata[:rank_id]
    record_voice.attach(formdata[:record_voice])
  end

  def scoreRank
    if self.rank_id == 1
      self.score = (25 + self.anger + (0.25 * (self.energy + self.calm))).round
    elsif self.rank_id == 2
      self.score = (self.anger + (0.5 * (self.energy + self.calm))).round
    elsif self.rank_id == 3
      self.score = (self.anger * 2).round
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  skip_before_action :require_login, only: %i[create show]
  before_action :require_login, only: %i[loginresults likes likeresults]
  before_action :set_result, only: %i[show loginresults likeresults]

  def create
    @result = Result.new
    @result.empath(result_params)
    @result.user_id = logged_in? ? current_user.id : Settings.user[:guest]
    @result.scoreRank
    @result.start_date = Date.today
    @result.save!
    if params[:part] == 'all'
      render json: { url: result_path(@result) }
    else
      render json: { url: loginresults_result_path(@result) }
    end
  end

  def show; end

  def loginresults; end

  def likeresults; end

  def likes
    @like_results = current_user.like_results.includes(:user)
  end

  private

  def result_params
    params.permit(:record_voice, :rank_id, :part)
  end

  def set_result
    @result = Result.find(params[:id])
    @rank = Rank.find(@result.rank_id)
    @beginner_comment = Comment.beginner_comment(@result)
    @intermediate_comment = Comment.intermediate_comment(@result)
    @advanced_comment = Comment.advanced_comment(@result)
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_like.html.erb
<%= link_to likes_path(result_id: @result.id), method: :post do %>
  <span class='iconify like mx-auto mt-2' data-icon='ant-design:like-outlined' style='color: #ff9a62;'></span>
<% end %>

app/views/results/_like_button.html.erb
<% if current_user.like?(@result) %>
  <%= render 'results/unlike' %>
<% else %>
  <%= render 'results/like' %>
<% end %>

app/views/results/_unlike.html.erb
<%= link_to like_path(current_user.likes.find_by(result_id: @result.id)), method: :delete do %>
  <span class='iconify like unlike mx-auto mt-2' data-icon='ant-design:like-filled' style='color: #ff9a62;'></span>
<% end %>

app/views/results/likeresults.html.erb
<div id='container'>
  <h1 class='pt-2 resultName'><%= @result.user.name %>さんの結果は・・・</h1>
  <h2 class='pt-2 resultName'>難易度: <%= @rank.level %></h2>
  <p class='text-center pt-5 score'><span class='title'><%= @result.score %></span>点</p>

  <% if @rank.id == Settings.rank[:beginner] %>
    <p class='d-flex justify-content-end comment'><%= @beginner_comment %></p>
  <% elsif @rank.id == Settings.rank[:intermediate] %>
    <p class='d-flex justify-content-end comment'><%= @intermediate_comment %></p>
  <% else %>
    <p class='d-flex justify-content-end comment'><%= @advanced_comment %></p>
  <% end %>
</div>

<div class='button'>
  <%= render 'results/like_button' %>
  <% if @result.record_voice.attached? %>
    <%= audio_tag(url_for(@result.record_voice), controls: true, preload: 'metadata', class: 'audio mx-auto mt-2') %>
  <% else %>
    <p>申し訳ございません。録音に失敗しました。</p>
  <% end %>

  <%= link_to '戻る', likes_results_path, class: 'btn btn-light btn-rounded mx-auto mt-2' %>
  <%= link_to 'ホームへ戻る', root_path, class: 'btn btn-warning btn-rounded mx-auto mt-2' %>
</div>

app/views/results/likes.html.erb
<div id='container-user'>
  <div class='lead'>
    <h1>お気に入り一覧</h1>
  </div>

  <%= month_calendar events: @like_results do |date, results| %>
    <%= date.day %>

    <% results.each do |result| %>
        <%= link_to result.score, likeresults_result_path(result), class:'likescore' %>点
    <% end %>
  <% end %>
</div>

app/views/results/loginresults.html.erb
<div id='container'>
  <h1 class='pt-2 resultName'><%= @result.user.name %>さんの結果は・・・</h1>
  <h2 class='pt-2 resultName'>難易度: <%= @rank.level %></h2>

  <% if [@result.anger, @result.sorrow, @result.joy, @result.energy, @result.calm].sum.zero? %>
    <p>エラーが発生しています。</p>
  <% else %>
    <p class='text-center pt-5 score'><span class='title'><%= @result.score %></span>点</p>
  <% end %>

  <% if @rank.id == Settings.rank[:beginner] %>
    <p class='d-flex justify-content-end comment'><%= @beginner_comment %></p>
  <% elsif @rank.id == Settings.rank[:intermediate] %>
    <p class='d-flex justify-content-end comment'><%= @intermediate_comment %></p>
  <% else %>
    <p class='d-flex justify-content-end comment'><%= @advanced_comment %></p>
  <% end %>

  <% if @result.score >= Settings.score[:standard] %>
    <p class='d-flex justify-content-end master'><span class="iconify" data-icon="material-symbols:perm-device-information-outline-sharp" style="color: #ff9a62; font-size: 50px;"></span><%= @result.user.name %>さんはしつけマスターとなったことをお知らせします。</p>
  <% end %>
</div>

<div class='button'>
  <%= render 'results/like_button' %>
  <% if @result.record_voice.attached? %>
    <%= audio_tag(url_for(@result.record_voice), controls: true, preload: 'metadata', class: 'mx-auto mt-2') %>
  <% else %>
    <p>申し訳ございません。録音に失敗しました。</p>
    <%= link_to 'もう一度やりなおす', ranks_path(next: 'step'), class: 'btn btn-dark btn-rounded mx-auto mt-2' %>
  <% end %>

  <% if @result.score >= Settings.score[:standard] %>
    <%= link_to 'https://twitter.com/share?url=#{request.url}&text=難易度:#{@rank.level}をマスターしました。%0a%0aあなたもペットに理想的なしつけを身につけませんか？', target: '_blank', class: 'btn btn-info btn-rounded mx-auto mt-2' do %>
      <i class='fab fa-twitter'></i>結果をshareしよう！
    <% end %>
  <% else %>
    <%= link_to 'https://twitter.com/share?url=#{request.url}&text=しつけ度『難易度:#{@rank.level}が#{@result.score}点』だったよ！%0a%0aあなたもペットに理想的なしつけを身につけませんか？', target: '_blank', class: 'btn btn-info btn-rounded mx-auto mt-2' do %>
      <i class='fab fa-twitter'></i>結果をshareしよう！
    <% end %>
  <% end %>

  <%= link_to 'もう一度挑戦する', ranks_path(next: 'step'), class: 'btn btn-success btn-rounded mx-auto mt-2' %>
  <%= link_to 'ホームへ戻る', root_path, class: 'btn btn-warning btn-rounded mx-auto mt-2' %>
</div>

app/views/results/show.html.erb
<div id='container'>
  <% if logged_in? %>
    <h1 class='pt-2 resultName'><%= @result.user.name %>さんの結果は・・・</h1>
    <h2 class='pt-2 resultName'>難易度: <%= @rank.level %></h2>
  <% else %>
    <h1 class='pt-2 resultName'>あなたの結果は・・・</h1>
  <% end %>

  <% if [@result.anger, @result.sorrow, @result.joy, @result.energy, @result.calm].sum.zero? %>
    <p>エラーが発生しています。</p>
  <% else %>
    <p class='text-center pt-5 score'><span class='title'><%= @result.score %></span>点</p>
  <% end %>

  <% if @rank.id == Settings.rank[:beginner] %>
    <p class='d-flex justify-content-end comment'><%= @beginner_comment %></p>
  <% elsif @rank.id == Settings.rank[:intermediate] %>
    <p class='d-flex justify-content-end comment'><%= @intermediate_comment %></p>
  <% else %>
    <p class='d-flex justify-content-end comment'><%= @advanced_comment %></p>
  <% end %>
</div>

<div class='button'>
  <% if logged_in? %>
    <%= render 'results/like_button' %>
  <% end %>
  <% if @result.record_voice.attached? %>
    <%= audio_tag(url_for(@result.record_voice), controls: true, preload: 'metadata', class: 'audio mx-auto mt-2') %>
  <% else %>
    <p>申し訳ございません。録音に失敗しました。</p>
    <%= link_to 'もう一度やりなおす', ranks_path, class: 'btn btn-dark btn-rounded mx-auto mt-2' %>
  <% end %>

  <%= link_to 'https://twitter.com/share?url=#{request.url}&text=しつけ度『難易度:#{@rank.level}が#{@result.score}点』だったよ！%0a%0aあなたもペットに理想的なしつけを身につけませんか？', target: '_blank', class: 'btn btn-info btn-rounded mx-auto mt-2' do %>
    <i class='fab fa-twitter'></i>結果をshareしよう！
  <% end %>

  <% if logged_in? %>
    <%= link_to 'ホームへ戻る', root_path, class: 'btn btn-warning btn-rounded mx-auto mt-2' %>
    <%= link_to 'もう一度挑戦する', ranks_path, class: 'btn btn-secondary btn-rounded mx-auto mt-2' %>
    <% if @result.score >= Settings.score[:standard] %>
      <%= link_to 'NEXT STEP', ranks_path(next: 'step'), class: 'btn btn-success btn-rounded mx-auto mt-2' %>
    <% end %>
  <% else %>
    <%= link_to 'ホームへ戻る', root_path, class: 'btn btn-warning btn-rounded mx-auto mt-2' %>
  <% end %>
</div>