config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'
  get 'privacy', to: 'tops#privacy'
  get 'terms', to: 'tops#terms'

  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :results, only: %i[show create] do
    member do
      get 'loginresults'
      get 'likeresults'
    end
    collection do
      get :likes
    end
  end

  resources :ranks, only: %i[index] do
    member do
      get 'record'
      get 'login_record'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :diaries

  resources :users do
    resources :attachments, controller: 'users/attachments', only: %i[destroy]
  end
end

app/models/rank.rb
class Rank < ApplicationRecord
  has_many :results, dependent: :destroy

  validates :level, length: { maximum: 50 }, presence: true
  validates :subtitle, length: { maximum: 255 }
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  skip_before_action :require_login, only: %i[index record]
  before_action :require_login, only: %i[login_record]
  before_action :set_rank, only: %i[record login_record]

  def index
    @beginner = Rank.find(Settings.rank[:beginner])
    @intermediate = Rank.find(Settings.rank[:intermediate])
    @advanced = Rank.find(Settings.rank[:advanced])
  end

  def record; end

  def login_record
    @user = current_user
  end

  private

  def set_rank
    @rank = Rank.find(params[:id])
  end
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/views/ranks/index.html.erb
<div id='container-user'>
  <div class='lead'>
    <h1>難易度選択</h1>
  </div>
  <% if current_page?(ranks_path(next: 'step')) %>
    <div class='row'>
      <div class='col-sm-6'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'><%= @beginner.level %></h5>
            <p class='card-text'><%= @beginner.subtitle %></p>
            <%= link_to '挑戦する', login_record_rank_path(id: Settings.rank[:beginner], part: 'login', beginner: 'all'), class:'btn btn-primary beginner' %>
          </div>
        </div>
      </div>
      <div class='col-sm-6'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'><%= @intermediate.level %></h5>
            <p class='card-text'><%= @intermediate.subtitle %></p>
            <%= link_to '挑戦する', login_record_rank_path(id: Settings.rank[:intermediate], part: 'login', intermediate: 'all'), class:'btn btn-primary intermediate' %>
          </div>
        </div>
      </div>
      <div class='col-sm-6'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'><%= @advanced.level %></h5>
            <p class='card-text'><%= @advanced.subtitle %></p>
            <%= link_to '挑戦する', login_record_rank_path(id: Settings.rank[:advanced], part: 'login', advanced: 'all'), class:'btn btn-primary advanced' %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
      <div class='row'>
      <div class='col-sm-6'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'><%= @beginner.level %></h5>
            <p class='card-text'><%= @beginner.subtitle %></p>
            <%= link_to '挑戦する', record_rank_path(id: Settings.rank[:beginner], part: 'all', beginner: 'all'), class:'btn btn-primary beginner' %>
          </div>
        </div>
      </div>
      <div class='col-sm-6'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'><%= @intermediate.level %></h5>
            <p class='card-text'><%= @intermediate.subtitle %></p>
            <%= link_to '挑戦する', record_rank_path(id: Settings.rank[:intermediate], part: 'all', intermediate: 'all'), class:'btn btn-primary intermediate' %>
          </div>
        </div>
      </div>
      <div class='col-sm-6'>
        <div class='card'>
          <div class='card-body'>
            <h5 class='card-title'><%= @advanced.level %></h5>
            <p class='card-text'><%= @advanced.subtitle %></p>
            <%= link_to '挑戦する', record_rank_path(id: Settings.rank[:advanced], part: 'all', advanced: 'all'), class:'btn btn-primary advanced' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/ranks/login_record.html.erb
<div class='wrapper record'>
  <% if @rank.id == Settings.rank[:beginner] %>
    <div class='pt-2 rank'>難易度:<%= @rank.level %></div>
  <% elsif @rank.id == Settings.rank[:intermediate] %>
    <div class='pt-2 rank'>難易度:<%= @rank.level %></div>
  <% else %>
    <div class='pt-2 rank'>難易度:<%= @rank.level %></div>
  <% end %>
  <div class='swiper-container-login'>
    <div class='swiper-wrapper'>
      <% if current_user.images.present? %>
        <% current_user.images.each do |image| %>
          <div class='swiper-slide'>
            <%= image_tag image.variant(resize:'1200x400').processed, id: 'new-image' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <p id='record'><span class='iconify mic2' data-icon='entypo:mic'></span></p>
</div>
<div class='text-center'>
  <p id='sentence'>クリックで録音開始 ※5秒間計測</P><br>
  <p class='word'>一言で怒ってね</P>
</div>

<%= javascript_pack_tag 'audio' %>
<%= javascript_pack_tag 'recordSwiper' %>

app/views/ranks/record.html.erb
<div class='wrapper record'>
  <% if @rank.id == Settings.rank[:beginner] %>
    <div class='pt-2 rank'>難易度:<%= @rank.level %></div>
  <% elsif @rank.id == Settings.rank[:intermediate] %>
    <div class='pt-2 rank'>難易度:<%= @rank.level %></div>
  <% else %>
    <div class='pt-2 rank'>難易度:<%= @rank.level %></div>
  <% end %>
  <p id='record'><span class='iconify mic' data-icon='entypo:mic'></span></p>
</div>
<div class='text-center'>
  <p id='sentence'>クリックで録音開始 ※5秒間計測</P><br>
  <p class='word'>一言で怒ってね</P>
</div>
<%= javascript_pack_tag 'audio' %>