config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'
  get 'privacy', to: 'tops#privacy'
  get 'terms', to: 'tops#terms'

  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :results, only: %i[show create] do
    member do
      get 'loginresults'
      get 'likeresults'
    end
    collection do
      get :likes
    end
  end

  resources :ranks, only: %i[index] do
    member do
      get 'record'
      get 'login_record'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :diaries

  resources :users do
    resources :attachments, controller: 'users/attachments', only: %i[destroy]
  end
end

app/views/layouts/_before_login_header.html.erb
<nav class='navbar navbar-expand-sm navbar-light mt-3 mb-3'>
<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav4' aria-controls='navbarNav4' aria-expanded='false' aria-label='Toggle navigation'>
  <span class='navbar-toggler-icon'></span>
</button>
<div class='collapse navbar-collapse'>
  <ul class='navbar-nav'>
    <li class='nav-item'>
      <%= link_to 'Discipline-meter', root_path, class: 'title' %>
    </li>
  </ul>
  <div class='navbar-right'>
    <ul class='navbar-nav'>
      <li class='nav-item'>
      <%= link_to 'ユーザー登録', new_user_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error_messages' class='alert alert-danger'>
    <ul class='mb-0'>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class='alert alert-<%= message_type %>'><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<div class='footer'>
  <ul class='menu'>
    <li><%= link_to '利用規約', terms_path %></li>
    <li><%= link_to 'プライバシーポリシー', privacy_path %></li>
    <li><%= link_to 'お問い合わせ', 'https://forms.gle/oEB3kFiyf5j6mE4p6' %></li>
  </ul>
  <p class='copyright'>
    &copy; Discipline-meter
  </p>
</div>

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9C4JQCXXB7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-9C4JQCXXB7');
</script>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-expand-sm navbar-light mt-3 mb-3'>
<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav4' aria-controls='navbarNav4' aria-expanded='false' aria-label='Toggle navigation'>
  <span class='navbar-toggler-icon'></span>
</button>
<div class='collapse navbar-collapse'>
  <ul class='navbar-nav'>
    <li class='nav-item'>
      <%= link_to 'Discipline-meter', root_path, class: 'title' %>
    </li>
  </ul>
  <div class='navbar-right'>
    <ul class='navbar-nav'>
      <li class='nav-item'>
        <%= link_to 'お気に入り一覧', likes_results_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'しつけ成長記', diaries_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'ユーザー編集', edit_user_path(current_user), class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://code.iconify.design/2/2.2.1/iconify.min.js'></script>
    <link href='https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@400;500&display=swap' rel='stylesheet'>
    <link href='https://use.fontawesome.com/releases/v5.6.1/css/all.css' rel='stylesheet'>
    <script src='//unpkg.com/swiper/swiper-bundle.min.js'></script>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>
  </head>

  <body class='body'>
    <header>
      <% if logged_in? %>
        <%= render 'layouts/header' %>
      <% else %>
        <%= render 'layouts/before_login_header' %>
      <% end %>
    </header>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>